### ISSUE TITLE
Supabase Sql

### ISSUE THREAD

**Issue by Rstacx** [timtbdev/Next.js-Blog-App#1]
If you can provide supabase sql file.

**Comment by timtbdev** [comment]
Hi,
Sorry for a late reply. Let me know if you need anything else.
https://github.com/timtbdev/Next.js-Blog-App/tree/main/database_schema

**Comment by Rstacx** [comment]
```
{
  code: '23503',
  details: 'Key (author_id)=(ffa6add6-903f-4265-956e-388065b67e14) is not present in table "profiles".',
  hint: null,
  message: 'insert or update on table "drafts" violates foreign key constraint "drafts_author_id_fkey"'
}
```

Can you give me the updated sql?

**Comment by Chaitanya-NK** [comment]
I am facing the same issue @timtbdev 
{
  code: '23503',
  details: 'Key (author_id)=(97cbb3ce-c748-449a-a185-815a547b370e) is not present in table "profiles".',
  hint: null,
  message: 'insert or update on table "drafts" violates foreign key constraint "drafts_author_id_fkey"'
}
